icons_format = "{icon}"

[theme]
theme = "dracula"
[theme.overrides]
#idle_bg = "#123456"
#idle_fg = "#abcdef"
separator = "::"
separator_fg = "#000000"

[icons]
icons = "awesome4"

[icons.overrides]
refresh = "\uf021"
ban = "\uf05e"
#bat = ["|E|", "|_|", "|=|", "|F|"]
#bat_charging = "|^| "


#[[block]]
#block = "disk_space"
#path = "/"
#info_type = "available"
#alert_unit = "GB"
#interval = 20
#warning = 20.0
#alert = 10.0
#format = " $icon root: $available.eng(w:2) "

[[block]]
block = "custom"
icons_format = " {icon} "
command = "$HOME/.config/i3/scripts/ya-disk-status.sh"
json = true

[[block]]
block = "pomodoro"

[[block]]
block = "packages"

[[block]]
block = "memory"
format = " $icon$mem_used_percents.eng(w:2) $icon_swap$swap_used_percents.eng(w:2) "
#format_alt = ""

[[block]]
block = "nvidia_gpu"
interval = 1
#format = " $icon $utilization $temperature $clocks "
format = " $icon$utilization $temperature "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "battery"
#format = " $percentage {$time |}"
format = " $icon$percentage "
missing_format = ""

[[block]]
block = "backlight"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "


[[block]]
block = "custom"
command = ''' $HOME/.config/i3/scripts/xkblayout-state print '%s' '''
